default_stages:
  - commit
  - manual
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.2.1'
    hooks:
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: string-tables-syntax-check
        name: String tables syntax check
        description: This hook will do lighwight stringtables checks
        entry: python check/st-tool.py check --reference default/stringtables/en.txt
        language: python
        files: 'default/stringtables/[a-z]{2}\.txt'
        types: [ text ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.8.0'
    hooks:
      - id: mypy
        name: focs.py type checks with mypy
        files: "(default/scripting/.*.py)|(check/check_file_changed/.*.py)"
        exclude: "^default/scripting/focs/.*.py"
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.350
    hooks:
      - id: pyright
        name: focs.py type checks with pyright
        files: "(default/scripting/.*.py)|(check/check_file_changed/.*.py)"
