name: "Lint PY FOCS"

on:
  workflow_call:
jobs:
  lint-py-focs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install development dependencies
        run: pip install -r default/python/requirements-dev.txt
      - name: Lint Python FOCS files with ty
        run: ty check .
      - name: Lint Python FOCS files with pyright
        run: pyright