name: String tables checks
on:
  workflow_call:
jobs:
  lint-string-tables:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check en string table is formatted properly
        run: |
          ./check/st-tool.py format default/stringtables/en.txt
      - name: Validate string tables
        run: |
          ./check/st-tool.py check --reference default/stringtables/en.txt default/stringtables/??.txt
