name: "Build master"
on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - 'snap/**'
      - '*.md'
      - 'check/**'
      - 'default/**'
      - 'test-scripting/**'
      - '.github/ISSUE_TEMPLATE/**'
      - "pyproject.toml"
jobs:
  android:
    uses: ./.github/workflows/_build-android.yml
  macos:
    strategy:
      matrix:
        os: [ macos-11, macos-12, macos-13 ]
    uses: ./.github/workflows/_build-macos.yml
    with:
      os: ${{ matrix.os }}
  ubuntu:
    uses: ./.github/workflows/_build-ubuntu.yml
  windows:
    uses: ./.github/workflows/_build-windows.yml
  windows-msvc:
    uses: ./.github/workflows/_build-windows-msvs.yml
  docker:
    uses: ./.github/workflows/_build-docker.yml
  snapcraft:
    uses: ./.github/workflows/_build_snapcraft.yml
  discord-notify-success: #  sample messages just for demo purposes
    uses: ./.github/workflows/_discord.yml
    needs:
      - android
      - macos
      - ubuntu
      - windows
      - docker
      - snapcraft
    if: failure()
    with:
      title: 'FreeOrion build master'
      webhook: ${{ secrets.DISCORD_WEBHOOK }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
