name: "Weekly"
on:
  push:
    branches: [ 'weekly-test-builds' ]
jobs:
  macos:
    uses: ./.github/workflows/_build-macos.yml
    with:
      os: 'macos-14'
      weekly-deploy: true
    secrets:
      DEPLOY_SSH_PASSWORD: ${{ secrets.DEPLOY_SSH_PASSWORD }}
  windows:
    uses: ./.github/workflows/_build-windows.yml
    secrets:
      DEPLOY_SSH_PASSWORD: ${{ secrets.DEPLOY_SSH_PASSWORD }}
  windows-msvc:
    uses: ./.github/workflows/_build-windows-msvs.yml
    secrets:
      DEPLOY_SSH_PASSWORD: ${{ secrets.DEPLOY_SSH_PASSWORD }}
