name: "Build PR"
on:
  pull_request:
    branches: [ 'master' ]
    types: ['opened', 'reopened', 'synchronize']
    paths-ignore:
      - '*'
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - 'snap/**'
      - '*.md'
      - 'check/**'
      - 'default/**'
      - 'test-scripting/**'
      - '.github/ISSUE_TEMPLATE/**'
      - "pyproject.toml"
      - ".pre-commit-config.yaml"
jobs:
  android:
    uses: ./.github/workflows/_build-android.yml
  macos:
    strategy:
      matrix:
        os: [ macos-13 ]
    uses: ./.github/workflows/_build-macos.yml
    with:
      os: ${{ matrix.os }}
  ubuntu:
    uses: ./.github/workflows/_build-ubuntu.yml
  windows-msvc:
    uses: ./.github/workflows/_build-windows-msvs.yml
