name: "Build master"
on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'msvc*/**'
      - 'check/**'
      - 'doc/**'
      - 'packaging/**'
      - 'snap/**'
      - '*.md'
      - 'check/**'
      - 'default/**'
      - 'test-scripting/**'

jobs:
  android:
    uses: ./.github/workflows/_build-android.yml
  macos:
    strategy:
      matrix:
        os: [ macos-11, macos-12, macos-13 ]
    uses: ./.github/workflows/_build-macos.yml
    with:
      os: ${{ matrix.os }}
  ubuntu:
    uses: ./.github/workflows/_build-ubuntu.yml
  windows:
    uses: ./.github/workflows/_build-windows.yml
  windows-msvc:
    uses: ./.github/workflows/_build-windows-msvs.yml
  docker:
    uses: ./.github/workflows/_build-docker.yml
  snapcraft:
    uses: ./.github/workflows/_build_snapcraft.yml
