name: AI linters and tests
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  lint-and-test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install development dependencies
        run: pip install -r default/python/requirements-dev.txt
      - name: Lint with flake8
        # Run from root to preserve full path in output
        run: >
          flake8 default/python
          --config=default/python/tox.ini
          --format="::error file=%(path)s,line=%(row)d,col=%(col)d::%(path)s:%(row)d:%(col)d: %(code)s %(text)s"
      - name: Lint FOCS with flake8
        # Run from root to preserve full path in output
        run: >
          flake8 default/scripting
          --config=default/scripting/tox.ini
          --format="::error file=%(path)s,line=%(row)d,col=%(col)d::%(path)s:%(row)d:%(col)d: %(code)s %(text)s"
      - name: Lint FOCS tests with flake8
        # Run from root to preserve full path in output
        run: >
          flake8 test-scripting
          --config=test-scripting/tox.ini
          --format="::error file=%(path)s,line=%(row)d,col=%(col)d::%(path)s:%(row)d:%(col)d: %(code)s %(text)s"
      - name: Lint st-tool with flake8
        # Run from root to preserve full path in output
        run: >
          flake8 check
          --config=default/scripting/tox.ini
          --format="::error file=%(path)s,line=%(row)d,col=%(col)d::%(path)s:%(row)d:%(col)d: %(code)s %(text)s"
      - name: Test with pytest
        # Run from root to preserve full path in output
        run: pytest -v default/python
      - name: Test st-tool with pytest
        # Run from root to preserve full path in output
        run: pytest -v check --doctest-modules --doctest-continue-on-failure
