name: AI linters and tests
on:
  pull_request:
    paths:
      - '.github/**'
      - 'check/st-tool.py'
      - 'default/python/**'
      - 'default/scripting/**'
      - 'test-scripting/**'
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  lint-and-test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install development dependencies
        run: pip install -r default/python/requirements-dev.txt
      - name: Lint AI code with flake8
        uses: ./.github/actions/flake8-lint
        with:
          directories: 'default/python cmake check'
          extra_args: '--builtins ""'
      - name: Lint FOCS with flake8
        uses: ./.github/actions/flake8-lint
        with:
          directories: 'default/scripting test-scripting'
      - name: Test with pytest
        # Run from root to preserve full path in output
        run: pytest -v default/python/tests
      - name: Test st-tool with pytest
        # Run from root to preserve full path in output
        run: pytest -v check --doctest-modules --doctest-continue-on-failure
